### ISSUE TITLE
Open cart modal on add to cart button click 

### ISSUE THREAD

**Issue by Tonya-sya** [addonify/addonify-floating-cart#321]
the function is enabled, but when adding a product to the cart, the modal cart does not open. 
The standard theme was enabled, plugins were disabled...

**Comment by h1dd3nsn1p3r** [comment]
Hi @Tonya-sya Can you please share your website URL?

**Comment by Tonya-sya** [comment]
https://www.luxperfume.com

**Comment by h1dd3nsn1p3r** [comment]
Can you check LiteSpeed cache plugin's settings and **disable** options: 

- Defer loading JavaScript
- Combine JavaScript

Once you disable these settings, flush all LiteSpeed cache.

**Comment by Tonya-sya** [comment]
they are off

**Comment by h1dd3nsn1p3r** [comment]
Please double check.

![image](https://github.com/addonify/addonify-floating-cart/assets/21140404/087edc7c-5bf2-41b0-9248-7c13fb5d09b8)

![image](https://github.com/addonify/addonify-floating-cart/assets/21140404/c36eae13-e9e4-4083-9c3b-90e15227dce5)

I can see some console errors. This is why the cart might not working. 

Another issue is that I am not being able to add any product in the cart since WordFence is blocking me when I try to visit the product single page.

![image](https://github.com/addonify/addonify-floating-cart/assets/21140404/af79ec74-0c4b-476a-b61f-bd4bcb4a001e)

**Comment by Tonya-sya** [comment]
write your ip address and I will give you access

other comments do not matter, the logged in user does not have all this, but the cart does not open
